### ISSUE TITLE
Breaks generated code when creating a derived builder

### ISSUE THREAD

**Issue by Rosomack** [REggar/auto-value-ignore-hash-equals#14]
``` 
@AutoValue
public abstract class Request {

    @IgnoreHashEquals public abstract int getId();

    public static Builder builder() {
        return new AutoValue_Request.Builder();
    }

    public abstract Builder toBuilder();

    @AutoValue.Builder
    public abstract static class Builder {

        public abstract Builder setId(int newId);

        public abstract Request build();
    }
}
```

The above example generates an incorrect class. The `toBuilder` method is mistaken for a field, but should be ignored.

**Comment by REggar** [comment]
Thanks for the bug report @Rosomack I will take a look.

**Comment by Rosomack** [comment]
Looks like this was a false alarm. Bug in the auto value library itself. 
Updating from 1.2 to 1.4.1 seems to have solved the issue!

Sorry about the confusion!

**Comment by REggar** [comment]
Yeah I was struggling to reproduce this, thanks for the update.
